name: Format, Lint, Test

on:
  workflow_dispatch:
  push:
    branches:
      - "feat/gh-actions"
  pull_request:
    paths-ignore:
      - .github/**

jobs:
  format_lint_test:
    # Check Formatting, Lint Code, Test Code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --dev-only

    - name: Check code-formatting with Black
      run: |
        python -m black . --check --diff

    - name: Lint code with Flake8
      run: |
        python -m flake8 --format='::error file=%(path)s,line=%(row)d,col=%(col)d::[flake8] %(code)s: %(text)s'

    - name: Test code with Pytest
      run: |
        pytest .
        echo "No tests found..."
